// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Blockstack = require("blockstack");

function getFileFromUser(file, username, app) {
  return Blockstack.getFile(file, {
              username: username,
              decrypt: false,
              app: app
            });
}

function getFileFromUserAndDecrypt(file, username) {
  return Blockstack.getFile(file, {
              username: username,
              decrypt: true
            });
}

function putFileEncryptedFor(path, content, pubKey) {
  return Blockstack.putFile(path, content, {
              encrypt: pubKey
            });
}

exports.getFileFromUser = getFileFromUser;
exports.getFileFromUserAndDecrypt = getFileFromUserAndDecrypt;
exports.putFileEncryptedFor = putFileEncryptedFor;
/* blockstack Not a pure module */
