---
groups:
- name: misthos-js
  jobs:
  - install-deps
  - test
  # - bump-minor
  # - bump-patch

jobs:
# - name: bump-minor
#   public: true
#   plan:
#     - { get: misthos-build, trigger: true,  passed: [deploy-testnet] }
#     - { get: build-version, params: {bump: minor}, passed: [deploy-testnet] }
#     - { put: build-version,                 params: {file: build-version/number} }

# - name: bump-patch
#   public: true
#   plan:
#     - { get: misthos-build, trigger: true, passed: [build] }
#     - { get: build-version, params: {bump: patch}, passed: [build] }
#     - { put: build-version,                params: {file: build-version/number} }

- name: install-deps
  plan:
  - aggregate:
    - {get: deps, trigger: true}
    - {get: pipeline-tasks}
    - {put: deps-version, params: {bump: minor}}
  - task: install-deps
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-js-pipeline}
      inputs:
      - name: pipeline-tasks
      - name: deps
      - name: deps-version
      outputs:
      - name: bundled-deps
      run:
        path: pipeline-tasks/ci/tasks/install-deps.sh
  - put: bundled-deps
    params:
      file: bundled-deps/bundled-misthos-js-deps-*.tgz

- name: test
  plan:
  - aggregate:
    - {get: repo, trigger: true}
    - {get: bundled-deps, trigger: true}
    - {get: pipeline-tasks}
    - {put: code-version, params: {bump: minor}}
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: misthosio/misthos-js-pipeline}
      inputs:
      - name: pipeline-tasks
      - name: bundled-deps
      - name: code-version
      - name: repo
      outputs:
      - name: bundled-code
      run:
        path: pipeline-tasks/ci/tasks/run-tests.sh
  - aggregate:
    - put: misthos-js-code
      params:
        file: bundled-code/misthos-js-*.tgz

# - name: build
#   plan:
#   - aggregate:
#     - {get: repo, passed: [test]}
#     - {get: misthos-code, trigger: true, passed: [test]}
#     - {get: build-version }
#     - {get: pipeline-tasks}
#   - task: build
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source: {repository: misthosio/misthos-web-pipeline}
#       inputs:
#       - name: pipeline-tasks
#       - name: misthos-code
#       - name: build-version
#       outputs:
#       - name: build
#       run:
#         path: pipeline-tasks/ci/tasks/build.sh
#   - put: misthos-build
#     params:
#       file: build/misthos-build-*.tgz

resources:
- name: repo
  type: git
  source:
    ignore_paths: [infra/*, ci/*, Makefile]
    uri: git@github.com:misthosio/misthos-js.git
    branch: master
    private_key: ((github-ssh-key.private_key))
- name: deps
  type: git
  source:
    paths: [yarn.lock]
    uri: git@github.com:misthosio/misthos-js.git
    branch: master
    private_key: ((github-ssh-key.private_key))
- name: bundled-deps
  type: gcs-resource
  source:
    bucket: artifact-cache
    json_key: ((gcp-service-account))
    regexp: bundled-misthos-js-deps-v(.*)-.*.tgz
- name: misthos-js-code
  type: gcs-resource
  source:
    bucket: artifact-cache
    json_key: ((gcp-service-account))
    regexp: misthos-js-code-v(.*)-.*.tgz
# - name: misthos-js-build
#   type: gcs-resource
#   source:
#     bucket: artifact-cache
#     json_key: ((gcp-service-account))
#     regexp: misthos-js-build-v(.*).tgz
- name: deps-version
  type: semver
  source:
    initial_version: 0.2.0
    driver: gcs
    bucket: artifact-cache
    key: versions/misthos-deps-version
    json_key: ((gcp-service-account))
- name: code-version
  type: semver
  source:
    initial_version: 0.2.0
    driver: gcs
    bucket: artifact-cache
    key: versions/misthos-code-version
    json_key: ((gcp-service-account))
# - name: build-version
#   type: semver
#   source:
#     initial_version: 0.2.0
#     driver: gcs
#     bucket: artifact-cache
#     key: versions/misthos-build-version
#     json_key: ((gcp-service-account))
- name: pipeline-tasks
  type: git
  source:
    uri: git@github.com:misthosio/misthos-js.git
    branch: master
    paths: [ci/tasks/*, Makefile]
    private_key: ((github-ssh-key.private_key))

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
