// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var BitcoinjsLib = require("bitcoinjs-lib");

function generateKeyPair() {
  return BitcoinjsLib.ECPair.makeRandom().toWIF();
}

function encodeSharedData(data) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "addresses",
                Json_encode.array((function (prim) {
                        return prim;
                      }), data[/* addresses */0])
              ],
              /* [] */0
            ]);
}

exports.generateKeyPair = generateKeyPair;
exports.encodeSharedData = encodeSharedData;
/* Json_encode Not a pure module */
