// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Bitcoin = require("./ffi/Bitcoin.bs.js");
var BitcoinjsLib = require("bitcoinjs-lib");

function bufToHex(buf) {
  return buf.toString("hex");
}

function bufFromHex(param) {
  return Buffer.from(param, "hex");
}

function publicKeyFromKeyPair(pair) {
  return pair.publicKey.toString("hex");
}

function privateKeyFromKeyPair(pair) {
  return pair.privateKey.toString("hex");
}

function storagePrefix(appPubKey) {
  return Bitcoin.Address[/* fromKeyPair */2](BitcoinjsLib.ECPair.fromPublicKey(bufFromHex(appPubKey), {
                  network: BitcoinjsLib.networks.bitcoin
                }));
}

exports.bufToHex = bufToHex;
exports.bufFromHex = bufFromHex;
exports.publicKeyFromKeyPair = publicKeyFromKeyPair;
exports.privateKeyFromKeyPair = privateKeyFromKeyPair;
exports.storagePrefix = storagePrefix;
/* Bitcoin Not a pure module */
